name: Python package

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      docker:
        image: python:3.11
        options: --user root

    steps:
        - uses: actions/checkout@v2
        - name: Build and Run Docker Container
          env:
            GH_PAT: ${{ secrets.GH_PAT }}
          run: |
            docker build --build-arg REPO_URL=https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com/${{ github.repository }}.git@${{ github.sha }} -t python-app-test -f tests/Dockerfile .
            docker run python-app-test
